name: cs_crash
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  in_app_review: ^2.0.9
  shared_preferences: ^2.3.3
  vibration: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: assets/icon.png
  android: true
  adaptive_icon_background: "#292353"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true
  ios: true
  web:
    generate: true
  macos:
    generate: true
  windows:
    generate: true
